name: Test SemVer

on:
 push:

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  semver:

    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - name: Install git
      run: |
        sudo apt-get update
        sudo apt-get install git
        git --version

    - name: Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: 0   
       
    - uses: paulhatch/semantic-version@master
      id: semantic-version

    - name: Output
      run: 
        echo ${{steps.semantic-version.outputs.version }}

    - name: Create tag
      run: |
        git config user.email "impks27"
        git config user.name "impks27"
        git tag -a ${{steps.semantic-version.outputs.version }} HEAD -m "Tag ${{steps.semantic-version.outputs.version }}"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{steps.semantic-version.outputs.version }}

    - name: Show tags
      run: |
        git push origin --tags
