name: Test SemVer

on:
 push:

jobs:
  semver:

    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - name: Install git
      run: |
        sudo apt-get update
        sudo apt-get install git
        git --version

    - name: Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: 0   
       
    - uses: paulhatch/semantic-version@master
      id: semantic-version

    - name: Create tag
      uses: actions/github-script@v5
      with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/<tagname>',
              sha: context.sha
            })
