name: Test SemVer

on:
 push:

permissions:
  actions: read|write|none
  checks: read|write|none
  contents: read|write|none
  deployments: read|write|none
  id-token: read|write|none
  issues: read|write|none
  discussions: read|write|none
  packages: read|write|none
  pages: read|write|none
  pull-requests: read|write|none
  repository-projects: read|write|none
  security-events: read|write|none
  statuses: read|write|none

jobs:
  semver:

    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - name: Install git
      run: |
        sudo apt-get update
        sudo apt-get install git
        git --version

    - name: Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: 0   
       
    - uses: paulhatch/semantic-version@master
      id: semantic-version

    - name: Create tag
      uses: actions/github-script@v5
      with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.semantic-version.output.version_tag}}',
              sha: context.sha
            })
