name: Test SemVer
##########
on:
 push:

jobs:
  semver:

    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    runs-on: ubuntu-latest

    steps:
    - name: Install git
      run: |
        sudo apt-get update
        sudo apt-get install git
        git --version

    - name: Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: 0   
       
    - uses: paulhatch/semantic-version@master
      id: semantic-version
      with:
        tag_prefix: ""
        major_pattern: "[MAJOR]"
        minor_pattern: "[MINOR]"


    - name: Output
      run: 
        echo ${{steps.semantic-version.outputs.version_tag }}

    - name: Create tag
      run: |
        git config user.email "impks27"
        git config user.name "impks27"
        git tag -a ${{steps.semantic-version.outputs.version_tag }} HEAD -m "Tag ${{steps.semantic-version.outputs.version_tag }}"
        git push origin --tags
    - name: Show tags
      run: |
        git tag
