name: Test SemVer

on:
 push:

jobs:
  semver:

    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - name: Install git
      run: |
        sudo apt-get update
        sudo apt-get install git
        git --version

    - name: Checkout
      uses: actions/checkout@v2
      with:
       fetch-depth: 0   
       
    - uses: paulhatch/semantic-version@master
