name: Test SemVer

on:
 push:

jobs:
  semver:

    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
    - name: Install git
      run: |
        sudo apt install git
    
    - uses: paulhatch/semantic-version@master
